import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StoreProvider } from '../storeProvider';
import { Toaster } from '@/components/ui/toaster';
import { AdminSideBar } from '@/components/sidebar/adminSideBar';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={poppins.className}>
            <Header />
            {children}
            <Footer />
            <Toaster />
        </body>
      </html>
    </StoreProvider>
  );
}
