import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StoreProvider } from '../storeProvider';
import { Toaster } from '@/components/ui/toaster';
import { AdminSideBar } from '@/components/sidebar/adminSideBar';

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: 'WearDrobe',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
        <html lang="en">
        <body className={inter.className}>
            <Header />
                {children}
            <Footer />
            <Toaster />
        </body>
        </html>
    </StoreProvider>
  );
}
