import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../globals.css';
import { Toaster } from 'sonner';
import BrickPhotoBackground from '../_components/BrickPhotoBackground';
import MarqueeBackground from '../_components/MarqueeBackground';

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: 'WearDrobe',
  description: 'Generated by create next app',
};

export var randomizer = Math.random() < 0.5;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
    

    return (
        <html lang="en">
            <body className={inter.className}>
                <div className='h-screen flex justify-center items-center relative overflow-hidden'>
                    { randomizer ? <BrickPhotoBackground /> : <MarqueeBackground/> }
                    <span className="absolute bottom-4 right-[5%] font-thin text-base text-white items-start hidden lg:flex">WearDrobe <span className="text-xs">&copy;</span></span>
                    { children }
                    <Toaster position="top-center" richColors />
                </div>
            </body>
        </html>
    );
}
