
export async function listWarehouse() {
    return [
        {
            warehouseName: 'Lagenda Sumatera',
            coordinate: '278,34',
            address: 'Gang Rustam, Petisah Tengah, Medan Petisah, Medan, Indonesia',
            city_id: 'Medan',
            province_id: 'Sumatera Utara',
            province: 'Sumatera Utara',
            type: 'Kota',
            city_name: 'Medan',
            postal_code: '20228',
            createdAt: new Date('2024-07-04 09:17:40.484'),
            adminID: null,
        },
        {
            warehouseName: 'Pangkalan Ujung',
            coordinate: '318,32',
            address: 'Jalan Perintis Kemerdekaan, Ujung Gurun, Padang, Indonesia',
            city_id: 'Padang',
            province_id: 'Sumatera Barat',
            province: 'Sumatera Barat',
            type: 'Kota',
            city_name: 'Padang',
            postal_code: '25112',
            createdAt: new Date('2024-07-04 11:11:00.746'),
            adminID: null,
        },
        {
            warehouseName: 'Jantung Indonesia',
            coordinate: '152,6',
            address: 'Transjakarta Busway Koridor 2, Menteng - Central Jakarta, Gambir, Jakarta Pusat, Indonesia',
            city_id: 'Jakarta Pusat',
            province_id: 'DKI Jakarta',
            province: 'DKI Jakarta',
            type: 'Kota',
            city_name: 'Jakarta Pusat',
            postal_code: '10540',
            createdAt: new Date('2024-07-04 09:48:40.216'),
            adminID: null,
        },
        {
            warehouseName: 'Wong Kito',
            coordinate: '327,33',
            address: 'Jalan Rawa Jaya, Kemuning, Palembang, Indonesia',
            city_id: 'Palembang',
            province_id: 'Sumatera Selatan',
            province: 'Sumatera Selatan',
            type: 'Kota',
            city_name: 'Palembang',
            postal_code: '30111',
            createdAt: new Date('2024-07-04 11:08:31.808'),
            adminID: null,
        },
        {
            warehouseName: 'Jaya Abadi',
            coordinate: '398,10',
            address: 'Jalan Imam Barjo, RW 05, Pleburan, Semarang Selatan, Semarang, Indonesia',
            city_id: 'Semarang',
            province_id: 'Jawa Tengah',
            province: 'Jawa Tengah',
            type: 'Kabupaten',
            city_name: 'Semarang',
            postal_code: '50511',
            createdAt: new Date('2024-07-04 11:09:41.242'),
            adminID: null,
        },
        {
            warehouseName: 'Paradise Breeze',
            coordinate: '17,1',
            address: 'Gang Kingkong 4b, Kuta - Kabupaten Badung - Bali - Indonesia, Kuta, Badung, Indonesia',
            city_id: 'Kuta',
            province_id: 'Bali',
            province: 'Bali',
            type: 'Kabupaten',
            city_name: 'Badung',
            postal_code: '80351',
            createdAt: new Date('2024-07-04 09:41:17.174'),
            adminID: null,
        },
        {
            warehouseName: 'Paling Kiri',
            coordinate: '20,21',
            address: 'Jalan Nyak Adam Kamil II, Neusu Jaya, Baiturrahman, Banda Aceh, Indonesia',
            city_id: 'Banda Aceh',
            province_id: 'Nanggroe Aceh Darussalam (NAD)',
            province: 'Nanggroe Aceh Darussalam (NAD)',
            type: 'Kota',
            city_name: 'Banda Aceh',
            postal_code: '23238',
            createdAt: new Date('2024-07-04 11:12:24.203'),
            adminID: null,
        },
        {
            warehouseName: 'Budi Pekerti',
            coordinate: '39,5',
            address: 'Jalan Desa Projo Taman Sari, Bangunharjo, Sewon, Bantul, Indonesia',
            city_id: 'Bantul',
            province_id: 'DI Yogyakarta',
            province: 'DI Yogyakarta',
            type: 'Kabupaten',
            city_name: 'Bantul',
            postal_code: '55715',
            createdAt: new Date('2024-07-04 11:07:44.657'),
            adminID: null,
        },
        {
            warehouseName: 'Pemuda Jawa Timur',
            coordinate: '444,11',
            address: 'Jalan Raya Gubeng 54, Gubeng - Surabaya - East Java, Surabaya, Indonesia',
            city_id: 'Surabaya',
            province_id: 'Jawa Timur',
            province: 'Jawa Timur',
            type: 'Kota',
            city_name: 'Surabaya',
            postal_code: '60119',
            createdAt: new Date('2024-07-04 11:10:25.319'),
            adminID: null,
        },
        {
            warehouseName: 'Digital Tech Asri',
            coordinate: '23,9',
            address: 'Jalan Asia Afrika 141-149, Bandung - Jawa Barat, Bandung, Indonesia',
            city_id: 'Bandung',
            province_id: 'Jawa Barat',
            province: 'Jawa Barat',
            type: 'Kota',
            city_name: 'Bandung',
            postal_code: '40111',
            createdAt: new Date('2024-07-04 09:43:15.795'),
            adminID: null,
        },
        {
            warehouseName: 'Sulawesi Punya',
            coordinate: '254,28',
            address: 'Jalan Rusa, Maricaya, Makassar, Indonesia',
            city_id: 'Makassar',
            province_id: 'Sulawesi Selatan',
            province: 'Sulawesi Selatan',
            type: 'Kota',
            city_name: 'Makassar',
            postal_code: '90111',
            createdAt: new Date('2024-07-04 11:11:43.502'),
            adminID: null,
        },
    ];
}
